import { AdminUser, SOSIncident, ComplaintRecord, CounsellorAppointment, ClassAttendanceRecord, EventRecord, LibraryBookRecord, LibraryIssueRecord, BloodRequestRecord, StartupProfileRecord } from '@/types/common';

export const MOCK_ADMIN_USERS: AdminUser[] = [
  {
    id: 'u-101',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@univ.edu',
    role: 'ADMIN',
    campus: 'Main North Campus',
    department: 'Central Administration',
    isActive: true,
    createdAt: '2025-01-10',
    lastLogin: '2026-07-25 19:40',
  },
  {
    id: 'u-102',
    name: 'Commander Robert Vance',
    email: 'robert.vance@univ.edu',
    role: 'SECURITY',
    campus: 'Main North Campus',
    department: 'Campus Security & Safety',
    isActive: true,
    createdAt: '2025-02-01',
    lastLogin: '2026-07-25 21:10',
  },
  {
    id: 'u-103',
    name: 'Prof. Alan Turing',
    email: 'alan.turing@univ.edu',
    role: 'FACULTY',
    campus: 'Technology Hub East',
    department: 'Computer Science & AI',
    isActive: true,
    createdAt: '2025-01-15',
    lastLogin: '2026-07-25 15:20',
  },
  {
    id: 'u-104',
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@univ.edu',
    role: 'COUNSELLOR',
    campus: 'Main North Campus',
    department: 'Student Wellness & Counselling',
    isActive: true,
    createdAt: '2025-03-12',
    lastLogin: '2026-07-25 18:05',
  },
  {
    id: 'u-105',
    name: 'Elena Rostova',
    email: 'elena.rostova@univ.edu',
    role: 'LIBRARY_STAFF',
    campus: 'Central Knowledge Complex',
    department: 'University Library System',
    isActive: true,
    createdAt: '2025-04-20',
    lastLogin: '2026-07-25 17:30',
  },
  {
    id: 'u-106',
    name: 'Marcus Brody',
    email: 'marcus.brody@univ.edu',
    role: 'EVENT_ORGANISER',
    campus: 'Main North Campus',
    department: 'Student Cultural Affairs',
    isActive: true,
    createdAt: '2025-05-18',
    lastLogin: '2026-07-25 20:15',
  },
];

export const MOCK_SOS_INCIDENTS: SOSIncident[] = [
  {
    id: 'sos-901',
    referenceCode: 'SOS-2026-0881',
    studentId: 'std-551',
    studentName: 'Alex Rivera',
    studentPhone: '+1 (555) 234-5678',
    location: 'Science Block B - 3rd Floor East Wing',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    status: 'TRIGGERED',
    priority: 'CRITICAL',
    reportedAt: '2026-07-25 21:15',
    notes: 'Medical distress button activated via app',
  },
  {
    id: 'sos-902',
    referenceCode: 'SOS-2026-0880',
    studentId: 'std-412',
    studentName: 'Samantha Wu',
    studentPhone: '+1 (555) 987-6543',
    location: 'South Quad Hostel Gate 4',
    coordinates: { lat: 37.7752, lng: -122.418 },
    status: 'DISPATCHED',
    priority: 'HIGH',
    assignedOfficerId: 'u-102',
    assignedOfficerName: 'Commander Robert Vance',
    reportedAt: '2026-07-25 20:50',
    notes: 'Security team en route to location',
  },
  {
    id: 'sos-903',
    referenceCode: 'SOS-2026-0879',
    studentId: 'std-309',
    studentName: 'Jordan Miller',
    studentPhone: '+1 (555) 345-6789',
    location: 'Central Library Basement Carpark',
    coordinates: { lat: 37.7741, lng: -122.421 },
    status: 'RESOLVED',
    priority: 'MEDIUM',
    assignedOfficerId: 'u-102',
    assignedOfficerName: 'Commander Robert Vance',
    reportedAt: '2026-07-25 18:30',
    resolvedAt: '2026-07-25 18:52',
    notes: 'Escorted safely to main entrance',
  },
];

export const MOCK_COMPLAINTS: ComplaintRecord[] = [
  {
    id: 'cmp-301',
    referenceNumber: 'CMP-2026-1042',
    title: 'Faulty Air Conditioning in Lecture Hall 4B',
    description: 'The main HVAC unit is making a loud metallic grinding noise and blowing uncooled air during 9 AM lectures.',
    category: 'Facilities & Infrastructure',
    status: 'UNDER_REVIEW',
    isAnonymous: false,
    studentId: 'std-204',
    studentName: 'David Kim',
    assignedDepartment: 'Campus Maintenance Desk',
    assignedStaffId: 'u-101',
    assignedStaffName: 'Dr. Sarah Jenkins',
    createdAt: '2026-07-25 09:30',
    updatedAt: '2026-07-25 14:15',
    campus: 'Main North Campus',
    resolutionTimeHours: 12,
    internalNotes: [
      { id: 'n-1', author: 'Maintenance Desk', note: 'Technician dispatched to check condenser coil.', createdAt: '2026-07-25 11:00' }
    ]
  },
  {
    id: 'cmp-302',
    referenceNumber: 'CMP-2026-1041',
    title: 'Discrepancy in Mid-Term Attendance Percentage',
    description: 'Attendance for CS-301 on July 14th was marked absent despite physical submission of attendance sheet.',
    category: 'Academic Administration',
    status: 'ASSIGNED',
    isAnonymous: false,
    studentId: 'std-108',
    studentName: 'Rachel Green',
    assignedDepartment: 'Faculty of Computer Science',
    assignedStaffId: 'u-103',
    assignedStaffName: 'Prof. Alan Turing',
    createdAt: '2026-07-24 16:20',
    updatedAt: '2026-07-25 10:00',
    campus: 'Technology Hub East',
    resolutionTimeHours: 24,
  },
  {
    id: 'cmp-303',
    referenceNumber: 'CMP-2026-1040',
    title: 'Inadequate Lighting in West Hostel Walkway',
    description: 'Three lampposts along the pedestrian walkway near West Quad are completely dark after 8 PM.',
    category: 'Campus Safety & Lighting',
    status: 'RESOLVED',
    isAnonymous: true,
    assignedDepartment: 'Campus Security & Electrical',
    assignedStaffId: 'u-102',
    assignedStaffName: 'Commander Robert Vance',
    createdAt: '2026-07-23 21:00',
    updatedAt: '2026-07-25 11:30',
    campus: 'Main North Campus',
    resolutionTimeHours: 38,
  },
];

export const MOCK_COUNSELLOR_APPOINTMENTS: CounsellorAppointment[] = [
  {
    id: 'app-501',
    studentId: 'std-701',
    studentName: 'Emily Carter',
    studentEmail: 'emily.c@univ.edu',
    appointmentDate: '2026-07-26',
    timeSlot: '10:00 AM - 11:00 AM',
    status: 'CONFIRMED',
    topic: 'Academic Stress & Career Anxiety',
    restrictedNotes: 'Student requested guidance on balancing exam preparation with research assistantship.',
    followUpRequired: true,
  },
  {
    id: 'app-502',
    studentId: 'std-702',
    studentName: 'Lucas Vance',
    studentEmail: 'lucas.v@univ.edu',
    appointmentDate: '2026-07-26',
    timeSlot: '02:00 PM - 03:00 PM',
    status: 'REQUESTED',
    topic: 'Personal Counselling & Dorm Adjustment',
    followUpRequired: false,
  },
];

export const MOCK_ATTENDANCE_RECORDS: ClassAttendanceRecord[] = [
  {
    id: 'att-801',
    classCode: 'CS-401',
    className: 'Advanced Distributed Systems',
    subject: 'Computer Science',
    facultyId: 'u-103',
    facultyName: 'Prof. Alan Turing',
    date: '2026-07-25',
    totalStudents: 45,
    presentCount: 41,
    absentCount: 3,
    lateCount: 1,
    qrActive: true,
    students: [
      { studentId: 'std-101', studentName: 'Alex Rivera', rollNumber: 'CS2023-001', status: 'PRESENT' },
      { studentId: 'std-102', studentName: 'Samantha Wu', rollNumber: 'CS2023-002', status: 'PRESENT' },
      { studentId: 'std-103', studentName: 'Daniel Craig', rollNumber: 'CS2023-003', status: 'ABSENT' },
      { studentId: 'std-104', studentName: 'Maria Garcia', rollNumber: 'CS2023-004', status: 'LATE' },
    ],
  },
];

export const MOCK_EVENTS: EventRecord[] = [
  {
    id: 'evt-201',
    title: 'Annual Tech Hackathon 2026',
    description: '36-hour flagship innovation hackathon with AI, Cloud, and Sustainability tracks.',
    category: 'Hackathon & Tech',
    organiserName: 'Marcus Brody',
    date: '2026-07-28',
    venue: 'Grand Innovation Auditorium',
    capacity: 300,
    registeredCount: 284,
    attendedCount: 0,
    rewardPoints: 150,
    status: 'UPCOMING',
    subSessions: [
      { id: 'sub-1', name: 'Opening Ceremony & Keynote', time: '09:00 AM', venue: 'Main Stage' },
      { id: 'sub-2', name: 'AI Workshop by Industry Experts', time: '02:00 PM', venue: 'Lab 3B' },
    ],
  },
];

export const MOCK_BOOKS: LibraryBookRecord[] = [
  {
    id: 'bk-101',
    isbn: '978-0134685991',
    title: 'Effective Java (3rd Edition)',
    author: 'Joshua Bloch',
    category: 'Software Engineering',
    totalCopies: 10,
    availableCopies: 3,
    issuedCopies: 7,
    shelfLocation: 'Rack 14 - Section B',
    status: 'AVAILABLE',
  },
  {
    id: 'bk-102',
    isbn: '978-0201633610',
    title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
    author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
    category: 'Software Architecture',
    totalCopies: 8,
    availableCopies: 0,
    issuedCopies: 8,
    shelfLocation: 'Rack 14 - Section A',
    status: 'ISSUED',
  },
];

export const MOCK_LIBRARY_ISSUES: LibraryIssueRecord[] = [
  {
    id: 'iss-901',
    bookId: 'bk-101',
    bookTitle: 'Effective Java (3rd Edition)',
    studentId: 'std-204',
    studentName: 'David Kim',
    issueDate: '2026-07-10',
    dueDate: '2026-07-24',
    fineAmount: 15.00,
    status: 'OVERDUE',
  },
];

export const MOCK_BLOOD_REQUESTS: BloodRequestRecord[] = [
  {
    id: 'bld-401',
    patientName: 'University Medical Center Reserve',
    bloodGroup: 'O negative (O-)',
    unitsRequired: 4,
    hospitalName: 'St. Jude Academic Hospital',
    contactNumber: '+1 (555) 777-8899',
    requiredByDate: '2026-07-26',
    urgency: 'CRITICAL',
    status: 'PENDING',
    matchedDonorsCount: 18,
  },
];

export const MOCK_STARTUPS: StartupProfileRecord[] = [
  {
    id: 'stp-601',
    startupName: 'EcoTrack Energy',
    founderName: 'Liam Hemsworth',
    founderEmail: 'liam.h@ecotrack.io',
    category: 'CleanTech & IoT',
    pitchSummary: 'Smart micro-grid monitoring IoT sensors for university and commercial campuses.',
    stage: 'UNDER_REVIEW',
    fundingRequested: 50000,
    teamSize: 4,
    submittedAt: '2026-07-20',
    hiringPostsCount: 2,
  },
];
