"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, MapPin, Plus, TicketCheck, Users } from "lucide-react";
import type { CampusEventStatus } from "@/app/generated/prisma/enums";
import { EmptyState } from "@/components/feedback/empty-state";
import { ErrorState } from "@/components/feedback/error-state";
import { LoadingState } from "@/components/feedback/loading-state";
import { StatCard } from "@/components/shared/stat-card";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError, apiFetch } from "@/lib/api-client";
import type { CampusEventDto } from "@/lib/operational-types";

const statuses: CampusEventStatus[] = ["DRAFT", "UPCOMING", "ONGOING", "COMPLETED", "CANCELLED"];
export function EventOrganiserDashboardFeature() {
  const [events, setEvents] = useState<CampusEventDto[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: "", description: "", category: "Technology", date: "", venue: "", capacity: "100", rewardPoints: "50" });
  const load = useCallback(async () => { try { const response = await apiFetch<CampusEventDto[]>("/events?limit=100"); setEvents(response.data); setError(""); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "Unable to load events."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const metrics = useMemo(() => ({ registrations: events.reduce((sum, item) => sum + item.registrations.filter((entry) => entry.status !== "CANCELLED").length, 0), checkIns: events.reduce((sum, item) => sum + item.registrations.filter((entry) => entry.status === "CHECKED_IN").length, 0) }), [events]);
  async function createEvent(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch("/events", { method: "POST", body: JSON.stringify({ ...form, date: new Date(form.date).toISOString(), capacity: Number(form.capacity), rewardPoints: Number(form.rewardPoints), status: "UPCOMING" }) }); setOpen(false); setForm({ title: "", description: "", category: "Technology", date: "", venue: "", capacity: "100", rewardPoints: "50" }); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "Unable to create event."); } finally { setSaving(false); } }
  async function updateStatus(id: string, status: CampusEventStatus) { setSaving(true); try { await apiFetch(`/events/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "Unable to update event."); } finally { setSaving(false); } }
  async function checkIn(eventId: string, studentId: string) { setSaving(true); try { await apiFetch(`/events/${eventId}/check-in`, { method: "POST", body: JSON.stringify({ studentId }) }); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "Unable to check in participant."); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Loading campus events..." />;
  return <div className="space-y-6">{error && <ErrorState message={error} onRetry={() => void load()} />}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Events" value={events.length} description="All event records" icon={CalendarDays} /><StatCard title="Upcoming" value={events.filter((event) => event.status === "UPCOMING").length} description="Open for registrations" icon={TicketCheck} /><StatCard title="Registrations" value={metrics.registrations} description="Confirmed and waitlisted" icon={Users} /><StatCard title="Checked in" value={metrics.checkIns} description="Verified participation" icon={CheckCircle2} /></div><div className="flex justify-end"><Button onClick={() => setOpen(true)}><Plus /> Create event</Button></div>{events.length === 0 ? <EmptyState icon={CalendarDays} title="No events yet" description="Create an event to manage capacity and check-in." /> : <Card><CardContent className="overflow-x-auto p-0"><Table className="min-w-[920px]"><TableHeader><TableRow><TableHead>Event</TableHead><TableHead>Date / venue</TableHead><TableHead>Capacity</TableHead><TableHead>Participation</TableHead><TableHead>Status</TableHead><TableHead>Check-in</TableHead></TableRow></TableHeader><TableBody>{events.map((item) => { const registered = item.registrations.filter((entry) => entry.status === "REGISTERED" || entry.status === "CHECKED_IN"); const next = item.registrations.find((entry) => entry.status === "REGISTERED"); return <TableRow key={item.id}><TableCell><p className="font-medium">{item.title}</p><p className="max-w-xs truncate text-xs text-muted-foreground">{item.category} · {item.rewardPoints} Numix</p></TableCell><TableCell><p>{new Date(item.date).toLocaleString()}</p><p className="flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3" />{item.venue}</p></TableCell><TableCell>{registered.length}/{item.capacity}<p className="text-xs text-muted-foreground">{Math.max(0, item.capacity - registered.length)} available</p></TableCell><TableCell>{item.registrations.filter((entry) => entry.status === "CHECKED_IN").length} checked in<p className="text-xs text-muted-foreground">{item.registrations.filter((entry) => entry.status === "WAITLISTED").length} waitlisted</p></TableCell><TableCell><Select value={item.status} onValueChange={(value) => value && void updateStatus(item.id, value as CampusEventStatus)}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent>{statuses.map((status) => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></TableCell><TableCell>{next ? <Button size="sm" variant="outline" disabled={saving} onClick={() => void checkIn(item.id, next.studentId)}>Check in {next.student.name?.split(" ")[0] ?? "student"}</Button> : <StatusBadge status="No pending check-ins" />}</TableCell></TableRow>; })}</TableBody></Table></CardContent></Card>}
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Create campus event</DialogTitle><DialogDescription>Publish capacity, venue, rewards, and registration details.</DialogDescription></DialogHeader><form onSubmit={createEvent} className="space-y-4"><div className="space-y-1"><Label>Title</Label><Input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div className="space-y-1"><Label>Description</Label><Textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1"><Label>Category</Label><Input required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></div><div className="space-y-1"><Label>Date and time</Label><Input required type="datetime-local" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></div><div className="space-y-1"><Label>Venue</Label><Input required value={form.venue} onChange={(e) => setForm({ ...form, venue: e.target.value })} /></div><div className="space-y-1"><Label>Capacity</Label><Input required type="number" min="1" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: e.target.value })} /></div><div className="space-y-1"><Label>Reward Numix</Label><Input required type="number" min="0" value={form.rewardPoints} onChange={(e) => setForm({ ...form, rewardPoints: e.target.value })} /></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={saving} type="submit">Publish event</Button></DialogFooter></form></DialogContent></Dialog></div>;
}