export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "Campus Safety and Support API", version: "1.0.0", description: "Versioned backend contract for the hackathon MVP." },
  servers: [{ url: "/api/v1" }],
  components: {
    securitySchemes: { sessionCookie: { type: "apiKey", in: "cookie", name: "authjs.session-token" } },
    schemas: {
      ApiError: { type: "object", properties: { error: { type: "object", required: ["code", "message"], properties: { code: { type: "string" }, message: { type: "string" }, requestId: { type: "string" } } } } },
      Pagination: { type: "object", properties: { page: { type: "integer" }, limit: { type: "integer" }, total: { type: "integer" } } },
    },
  },
  paths: {
    "/health": { get: { summary: "Backend and integration status", responses: { "200": { description: "Healthy" } } } },
    "/users/me": { get: { summary: "Current profile", security: [{ sessionCookie: [] }], responses: { "200": { description: "Profile" } } }, patch: { summary: "Update current profile", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/auth/otp/request": { post: { summary: "Request email OTP", responses: { "200": { description: "Accepted" } } } },
    "/auth/otp/verify": { post: { summary: "Verify email OTP", responses: { "200": { description: "Verified" } } } },
    "/auth/password/reset": { post: { summary: "Reset password with a verified token", responses: { "200": { description: "Reset" } } } },
    "/sos": { get: { summary: "List permitted SOS incidents", security: [{ sessionCookie: [] }], responses: { "200": { description: "Incidents" } } }, post: { summary: "Create SOS incident", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/sos/{id}": { get: { summary: "SOS detail and history", security: [{ sessionCookie: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Incident" } } } },
    "/sos/{id}/status": { patch: { summary: "Advance SOS status", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" }, "409": { description: "Invalid transition" } } } },
    "/sos/{id}/cancel": { post: { summary: "Cancel open SOS as false alarm", security: [{ sessionCookie: [] }], responses: { "200": { description: "Cancelled" } } } },
    "/complaint-categories": { get: { summary: "List active complaint categories", responses: { "200": { description: "Categories" } } } },
    "/complaints": { get: { summary: "List permitted complaints", security: [{ sessionCookie: [] }], responses: { "200": { description: "Complaints" } } }, post: { summary: "Create named complaint", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/complaints/anonymous": { post: { summary: "Create anonymous complaint and receive tracking token", responses: { "201": { description: "Created" } } } },
    "/complaints/track": { post: { summary: "Track anonymous complaint", responses: { "200": { description: "Complaint" } } } },
    "/complaints/{id}/assignment": { patch: { summary: "Assign complaint", security: [{ sessionCookie: [] }], responses: { "200": { description: "Assigned" } } } },
    "/complaints/{id}/status": { patch: { summary: "Update complaint status", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/complaints/{id}/messages": { post: { summary: "Add complaint message", responses: { "201": { description: "Created" } } } },
    "/complaints/{id}/feedback": { post: { summary: "Submit resolution feedback", responses: { "201": { description: "Created" } } } },
    "/support/profiles": { get: { summary: "List mentors and counsellors", security: [{ sessionCookie: [] }], responses: { "200": { description: "Profiles" } } }, post: { summary: "Create or update support profile", security: [{ sessionCookie: [] }], responses: { "201": { description: "Saved" } } } },
    "/support/requests": { get: { summary: "List permitted support requests", security: [{ sessionCookie: [] }], responses: { "200": { description: "Requests" } } }, post: { summary: "Create support request", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/appointments": { get: { summary: "List appointments", security: [{ sessionCookie: [] }], responses: { "200": { description: "Appointments" } } }, post: { summary: "Atomically book a slot", security: [{ sessionCookie: [] }], responses: { "201": { description: "Booked" }, "409": { description: "Slot already booked" } } } },
    "/conversations/{id}/messages": { get: { summary: "List confidential messages", security: [{ sessionCookie: [] }], responses: { "200": { description: "Messages" } } }, post: { summary: "Send confidential message", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/support/chatbot": { post: { summary: "Constrained campus-resource assistant", security: [{ sessionCookie: [] }], responses: { "200": { description: "Structured resource answer" } } } },
    "/notifications": { get: { summary: "List notifications", security: [{ sessionCookie: [] }], responses: { "200": { description: "Notifications" } } } },
    "/attendance": { get: { summary: "Attendance contract scaffold", responses: { "501": { description: "Not implemented" } } } },
    "/events": { get: { summary: "Events contract scaffold", responses: { "501": { description: "Not implemented" } } } },
    "/rewards": { get: { summary: "Rewards contract scaffold", responses: { "501": { description: "Not implemented" } } } },
    "/library": { get: { summary: "Library contract scaffold", responses: { "501": { description: "Not implemented" } } } },
    "/blood-donors": { get: { summary: "Blood donor contract scaffold", responses: { "501": { description: "Not implemented" } } } },
    "/startups": { get: { summary: "Startup contract scaffold", responses: { "501": { description: "Not implemented" } } } },
  },
} as const;
