export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "Voxa Campus Platform API", version: "1.0.0", description: "Versioned backend contract for the Voxa platform." },
  servers: [{ url: "/api/v1" }],
  components: {
    securitySchemes: { sessionCookie: { type: "apiKey", in: "cookie", name: "authjs.session-token" } },
    schemas: {
      ApiError: { type: "object", properties: { error: { type: "object", required: ["code", "message"], properties: { code: { type: "string" }, message: { type: "string" }, requestId: { type: "string" } } } } },
      Pagination: { type: "object", properties: { page: { type: "integer" }, limit: { type: "integer" }, total: { type: "integer" } } },
    },
  },
  paths: {
    "/health": { get: { summary: "Backend and integration status", responses: { "200": { description: "Healthy" } } } },
    "/users/me": { get: { summary: "Current profile", security: [{ sessionCookie: [] }], responses: { "200": { description: "Profile" } } }, patch: { summary: "Update current profile", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/auth/otp/request": { post: { summary: "Request email OTP", responses: { "200": { description: "Accepted" } } } },
    "/auth/otp/verify": { post: { summary: "Verify email OTP", responses: { "200": { description: "Verified" } } } },
    "/auth/password/reset": { post: { summary: "Reset password with a verified token", responses: { "200": { description: "Reset" } } } },
    "/sos": { get: { summary: "List permitted SOS incidents", security: [{ sessionCookie: [] }], responses: { "200": { description: "Incidents" } } }, post: { summary: "Create SOS incident", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/sos/{id}": { get: { summary: "SOS detail and history", security: [{ sessionCookie: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Incident" } } } },
    "/sos/{id}/status": { patch: { summary: "Advance SOS status", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" }, "409": { description: "Invalid transition" } } } },
    "/sos/{id}/cancel": { post: { summary: "Cancel open SOS as false alarm", security: [{ sessionCookie: [] }], responses: { "200": { description: "Cancelled" } } } },
    "/complaint-categories": { get: { summary: "List active complaint categories", responses: { "200": { description: "Categories" } } } },
    "/complaints": { get: { summary: "List permitted complaints", security: [{ sessionCookie: [] }], responses: { "200": { description: "Complaints" } } }, post: { summary: "Create named complaint", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/complaints/anonymous": { post: { summary: "Create anonymous complaint and receive tracking token", responses: { "201": { description: "Created" } } } },
    "/complaints/track": { post: { summary: "Track anonymous complaint", responses: { "200": { description: "Complaint" } } } },
    "/complaints/{id}": { get: { summary: "Get permitted complaint detail", security: [{ sessionCookie: [] }], responses: { "200": { description: "Complaint" } } } },
    "/complaints/{id}/assignment": { patch: { summary: "Assign complaint", security: [{ sessionCookie: [] }], responses: { "200": { description: "Assigned" } } } },
    "/complaints/{id}/status": { patch: { summary: "Update complaint status", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/complaints/{id}/messages": { post: { summary: "Add complaint message", responses: { "201": { description: "Created" } } } },
    "/complaints/{id}/feedback": { post: { summary: "Submit resolution feedback", responses: { "201": { description: "Created" } } } },
    "/support/profiles": { get: { summary: "List mentors and counsellors", security: [{ sessionCookie: [] }], responses: { "200": { description: "Profiles" } } }, post: { summary: "Create or update support profile", security: [{ sessionCookie: [] }], responses: { "201": { description: "Saved" } } } },
    "/support/requests": { get: { summary: "List permitted support requests", security: [{ sessionCookie: [] }], responses: { "200": { description: "Requests" } } }, post: { summary: "Create support request", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/appointments": { get: { summary: "List appointments", security: [{ sessionCookie: [] }], responses: { "200": { description: "Appointments" } } }, post: { summary: "Atomically book a slot", security: [{ sessionCookie: [] }], responses: { "201": { description: "Booked" }, "409": { description: "Slot already booked" } } } },
    "/conversations/{id}/messages": { get: { summary: "List confidential messages", security: [{ sessionCookie: [] }], responses: { "200": { description: "Messages" } } }, post: { summary: "Send confidential message", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/support/lexa": { post: { summary: "Lexa campus-resource assistant", security: [{ sessionCookie: [] }], responses: { "200": { description: "Structured resource answer" } } } },
    "/notifications": { get: { summary: "List notifications", security: [{ sessionCookie: [] }], responses: { "200": { description: "Notifications" } } } },
    "/appointments/{id}/status": { patch: { summary: "Update appointment status", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" }, "409": { description: "Invalid transition" } } } },
    "/admin/users": { get: { summary: "List users", security: [{ sessionCookie: [] }], responses: { "200": { description: "Users" } } }, post: { summary: "Create user with roles", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" }, "409": { description: "Email already exists" } } } },
    "/admin/users/{id}/roles": { patch: { summary: "Replace user roles", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/admin/users/{id}/status": { patch: { summary: "Activate or suspend user", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" }, "400": { description: "Cannot suspend self" } } } },
    "/audit": { get: { summary: "List audit events", security: [{ sessionCookie: [] }], responses: { "200": { description: "Audit events" } } } },
    "/attendance": { get: { summary: "List permitted attendance sessions", security: [{ sessionCookie: [] }], responses: { "200": { description: "Sessions" } } }, post: { summary: "Create a session and active student roster", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/attendance/{id}": { patch: { summary: "Update attendance marks or QR state", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/events": { get: { summary: "List campus events", security: [{ sessionCookie: [] }], responses: { "200": { description: "Events" } } }, post: { summary: "Create campus event", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/events/{id}": { patch: { summary: "Update event status", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/events/{id}/registrations": { post: { summary: "Register with capacity and waiting list", security: [{ sessionCookie: [] }], responses: { "201": { description: "Registered" } } } },
    "/events/{id}/check-in": { post: { summary: "Check in registered participant", security: [{ sessionCookie: [] }], responses: { "200": { description: "Checked in" } } } },
    "/rewards": { get: { summary: "Rewards contract scaffold", responses: { "501": { description: "Not implemented" } } } },
    "/library": { get: { summary: "List catalogue and circulation", security: [{ sessionCookie: [] }], responses: { "200": { description: "Library data" } } }, post: { summary: "Add catalogue book", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/library/loans": { post: { summary: "Issue an available copy", security: [{ sessionCookie: [] }], responses: { "201": { description: "Issued" }, "409": { description: "Unavailable" } } } },
    "/library/loans/{id}/return": { post: { summary: "Return copy and calculate fine", security: [{ sessionCookie: [] }], responses: { "200": { description: "Returned" } } } },
    "/blood-donors": { get: { summary: "List requests and consented available donors", security: [{ sessionCookie: [] }], responses: { "200": { description: "Network" } } }, post: { summary: "Register donor or create request", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/blood-donors/requests/{id}": { patch: { summary: "Update request state", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
    "/startups": { get: { summary: "List permitted startup profiles", security: [{ sessionCookie: [] }], responses: { "200": { description: "Startups" } } }, post: { summary: "Submit startup profile", security: [{ sessionCookie: [] }], responses: { "201": { description: "Created" } } } },
    "/startups/{id}": { patch: { summary: "Review startup and assign mentor", security: [{ sessionCookie: [] }], responses: { "200": { description: "Updated" } } } },
  },
} as const;
