import type { RoleCode } from "@/app/generated/prisma/enums";

export const PERMISSIONS = {
  PROFILE_READ_SELF: "profile.read.self",
  PROFILE_UPDATE_SELF: "profile.update.self",
  SOS_CREATE: "sos.create",
  SOS_READ_OWN: "sos.read.own",
  SOS_READ_ALL: "sos.read.all",
  SOS_UPDATE_STATUS: "sos.update.status",
  COMPLAINT_CREATE: "complaint.create",
  COMPLAINT_READ_OWN: "complaint.read.own",
  COMPLAINT_READ_ALL: "complaint.read.all",
  COMPLAINT_ASSIGN: "complaint.assign",
  COMPLAINT_UPDATE_STATUS: "complaint.update.status",
  SUPPORT_REQUEST_CREATE: "support.request.create",
  SUPPORT_PROFILE_MANAGE: "support.profile.manage",
  APPOINTMENT_BOOK: "appointment.book",
  APPOINTMENT_MANAGE: "appointment.manage",
  CHAT_ACCESS: "chat.access",
  NOTIFICATION_READ: "notification.read",
  AUDIT_READ: "audit.read",
  ROLE_MANAGE: "role.manage",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  STUDENT: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.SOS_CREATE,
    PERMISSIONS.SOS_READ_OWN,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_READ_OWN,
    PERMISSIONS.SUPPORT_REQUEST_CREATE,
    PERMISSIONS.APPOINTMENT_BOOK,
    PERMISSIONS.CHAT_ACCESS,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  FACULTY: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_READ_OWN,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  COUNSELLOR: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.SUPPORT_PROFILE_MANAGE,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.CHAT_ACCESS,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  COORDINATOR: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.COMPLAINT_READ_ALL,
    PERMISSIONS.COMPLAINT_ASSIGN,
    PERMISSIONS.COMPLAINT_UPDATE_STATUS,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  SECURITY: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.SOS_READ_ALL,
    PERMISSIONS.SOS_UPDATE_STATUS,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  LIBRARY_STAFF: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  ADMIN: Object.values(PERMISSIONS),
};
